Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
== RESTART: C:/Users/user/AppData/Local/Programs/Python/Python36-32/123.py ==
Traceback (most recent call last):
  File "C:/Users/user/AppData/Local/Programs/Python/Python36-32/123.py", line 1, in <module>
    fin = open('test.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'
>>> 
=================== RESTART: C:/Users/user/Desktop/123.py ===================
123
>>> 
=================== RESTART: C:/Users/user/Desktop/123.py ===================
123
>>> 123
123
>>> 456
456
>>> 
=================== RESTART: C:/Users/user/Desktop/123.py ===================
123
>>> 
=================== RESTART: C:/Users/user/Desktop/123.py ===================
你好Python
Traceback (most recent call last):
  File "C:/Users/user/Desktop/123.py", line 7, in <module>
    with open('print_self_utf8.py', encoding='utf8') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'print_self_utf8.py'
>>> 
=================== RESTART: C:/Users/user/Desktop/123.py ===================
你好Python
Traceback (most recent call last):
  File "C:/Users/user/Desktop/123.py", line 7, in <module>
    with open('print_self_utf8.py', encoding='utf8') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'print_self_utf8.py'
>>> 
